fetch apps to users
deanshub/in-it pull request #7
Opened 2023-05-24 12:16 UTC by shamit6

2023-05-24 12:27 UTC, deanshub commented on packages/web/src/db/user.ts
> +const userSchema = new Schema<UserDocument & { apps: AppsDocument[] }>(
create `UserWithApps` type

2023-05-24 12:27 UTC, deanshub approved these changes

2023-05-24 12:31 UTC, deanshub commented on packages/web/src/app/api/user/[id]/route.ts
> +  const { id: userId } = params;
user should not come form params, it should come form the session

2023-05-24 12:32 UTC, deanshub requested changes
please refactor route to be /apps

2023-05-24 12:39 UTC, deanshub commented
move `user.ts` file to a directory within `db` called `models` and upper case the first latter of the file to be `User.ts`

2023-05-24 14:26 UTC, deanshub commented on packages/web/src/app/api/apps/route.ts
> +  // @ts-ignore
?

2023-05-24 14:26 UTC, deanshub commented on packages/web/src/app/api/apps/route.ts
> +  // TODO change to user db id
!

2023-05-24 14:27 UTC, deanshub commented on packages/web/src/db/dbConnect.ts
> +import '@/db/models/User';
now create an `index.ts` in `models` that should export all the models and here just import it

2023-05-24 15:51 UTC, deanshub commented on packages/web/src/db/models/App.ts
> +    },
I think we also need provider here, since repo can be the same in github and gitlab

2023-05-25 11:55 UTC, shamit6 commented on packages/web/src/db/models/App.ts
> +    },
The (url) repository will be different. isn't enough?

2023-05-25 12:03 UTC, shamit6 commented on packages/web/src/app/api/apps/route.ts
> +  await dbConnect();
https://github.com/vercel/next.js/blob/canary/examples/with-mongodb-mongoose/pages/api/pets/%5Bid%5D.js

2023-05-25 14:02 UTC, deanshub commented on packages/web/src/db/models/App.ts
> +    },
I didn't think it's going to be full url since it's there are many options depending on protocol

2023-05-26 06:45 UTC, deanshub commented on packages/web/src/app/api/apps/route.ts
> +  // TODO add provider to user.id
?

2023-05-28 07:04 UTC, deanshub approved these changes

2023-05-28 07:05 UTC, merged